# Generated by Django 6.0 on 2025-12-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('medical', 'Medical'), ('fire', 'Fire'), ('security', 'Security')], max_length=20)),
                ('location', models.JSONField()),
                ('details', models.TextField(blank=True)),
                ('urgency', models.CharField(default='medium', max_length=20)),
                ('contact_method', models.CharField(default='both', max_length=10)),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_by_uid', models.CharField(max_length=100)),
                ('display_code', models.CharField(default='ANON', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
