# Generated by Django 6.0 on 2025-12-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='emergency',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='contact_method',
            field=models.CharField(choices=[('chat', 'Chat Only'), ('call', 'Call Only'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='created_by_uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='urgency',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
